### ISSUE TITLE
Installation fails on Windows

### ISSUE THREAD

**Issue by serglider** [cezaraugusto/extension-create#13]
Installation fails on Windows because of the usage of UNIX-only executable "sh"

```
'sh' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! extension-create@0.4.4 preinstall: `sh preinstall.sh`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the extension-create@0.4.4 preinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\s-che\AppData\Roaming\npm-cache\_logs\2021-03-02T15_17_57_063Z-debug.log
Install for [ 'extension-create@latest' ] failed with code 1
```

**Comment by cezaraugusto** [comment]
thanks for reporting, @serglider! I'd love to see this fixed but have other priorities for the project, so feel free to push a PR if you will. I think Windows users looking for extension-create can use git bash that supports shell commands or maybe a tool such as [Cygwin](https://www.cygwin.com/).

**Comment by serglider** [comment]
#14 
created a PR

**Comment by cezaraugusto** [comment]
fixed vby https://github.com/cezaraugusto/extension-create/pull/14
