### ISSUE TITLE
Chrome in dev mode is very slow

### ISSUE THREAD

**Issue by jnnnthnn** [cezaraugusto/extension-create#134]
Extension.js seems really cool. I've been trying it out for a new project and noticed that the Chrome instance in dev mode seems extremely slow, both in loading/rendering pages and in managing browser interactions.

I didn't see this noted anywhere as expected behavior, so figured I'd open a ticket for it. Happy to try additional reproduction/diagnosis steps if useful.

# Reproduction steps

- Extension.js version: 1.8.0
- Chrome version: 126.0.6478.127
- OS: macOS 14.2.1 (23C71)

## 1. Run a basic project

```bash
npx extension create my-extension
cd my-extension
npm run dev
```

## 2. Load a webpage
E.g. https://github.com/

## 3. Notice slowness

https://github.com/user-attachments/assets/4b169a87-7924-41a4-9ca6-706fcc8d1665

Extension.js dev instance on the left, Chrome in incognito mode on the right

**Comment by cezaraugusto** [comment]
wow that's very slow. thanks a lot for putting it together.

I load Chrome with a bunch of changes in their [master preferences](https://github.com/extension-js/extension.js/blob/main/packages/run-chrome-extension/steps/RunChromePlugin/chrome/masterPreferences.ts) file, but most switches are for disabling features. maybe that's related
