### ISSUE TITLE
error in npx start

### ISSUE THREAD

**Issue by vKrypto** [cezaraugusto/extension-create#20]
I am new in npx, can anyone help me with this. 

I am getting this on execution of **npx extension-create start**

npm ERR! cb.apply is not a function  npm ERR! A complete log of this run can be found in: npm ERR!     /home/ashutosh/.npm/_logs/2021-07-29T22_36_15_037Z-debug.log Install for [ 'extension-create@latest' ] failed with code 1

**node --verison: 16.4.2
npx --verison : 10.2.2**

**Comment by cezaraugusto** [comment]
fixed in [v1.0.7](https://github.com/cezaraugusto/extension-create/releases/tag/v1.0.7). thanks!
