### ISSUE TITLE
Unable to run; erroneously claims address 127.0.0.1:8000 is in use

### ISSUE THREAD

**Issue by NerdyDeedsLLC** [cezaraugusto/extension-create#44]
No matter what I do, I cannot seem to get the thing to launch. I am consistently rebuked by an error informing me that its preferred localhost address is already in use. I experience this same effect with or without the `--port` flag, including after a clean boot, with literally no other web processes in use (see attached imagery below).

![image](https://github.com/cezaraugusto/extension-create/assets/43561032/40faf38e-51e6-47e4-b681-99805dff0816)

As you can see from the stack trace, I'm not seeing anything that would be a whole lotta help (though I have no issues spinning up servers through any other means, including atop 8000). 

Any ideas?

_I'm running on Wayland (GNOME 45.2)/Ubuntu 23.10, on a 12-core Intel i7 10750H with 32GB of memory, and well over a half terabyte free. Active shell is Bash v.5.2.15, npm is at v10.5.0, and node is on v20.9.0 (lts/iron)._

**Comment by cezaraugusto** [comment]
hi @NerdyDeedsLLC, thanks for reporting! It was indeed a bug.

I just patched it in v1.2.2. Running `npx extension-create@latest dev <extension-path>` (the `@latest` part is important -- `npx` cache is huge) should work on Linux as well.

Here's a local run pulling remote [historyOverride](https://github.com/GoogleChrome/chrome-extensions-samples/tree/main/api-samples/history/historyOverride) from Chrome Samples running on Ubuntu 22.04:

<img width="1196" alt="Screenshot 2024-03-21 at 11 50 10" src="https://github.com/cezaraugusto/extension-create/assets/4672033/4b723737-6118-4075-93fc-58d82f2af447">

> You can run the same command I did to assert it works:

```
npx extension-create dev https://github.com/GoogleChrome/chrome-extensions-samples/tree/main/api-samples/history/historyOverride
```

By the way, running it in `npx` is the best way to get to know the project, but for reliability, better to install it as a local dependency (via `npm install` or `yarn install` -- other package managers are not tested). I plan to add support for global installs soon.

Thanks for trying out `extension-create` and let me know if the issue you found is fixed on your end too :)
